#Tomcat
server:
  port: 8080
# DataSource
spring:
  datasource:
    dynamic:
      primary: eTag
      strict: false
      datasource:
        eTag:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/etag?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: root
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

mybatis:
  type-aliases-package: com.eTag.back.*.pojo
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

page helper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  auto-runtime-dialect: true


logging:
  level:
    com.eTag.back.* : DEBUG

file:
  upload-dir: C:\Users\jizhi\Downloads\
  api-path: http://172.17.168.89:8080/uploads/
  getApi: http://47.93.170.149:8080/device/getLabel
  postApi: http://47.93.170.149:8080/device/postLabel

