#Tomcat
server:
  port: 8080
# DataSource
spring:
  datasource:
    dynamic:
      primary: eTag
      strict: false
      datasource:
        eTag:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.8:3306/etag?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 961013ly

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

mybatis:
  type-aliases-package: com.eTag.back.*.pojo
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

page helper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  auto-runtime-dialect: true

logging:
  level:
     com.eTag.back.* : DEBUG

file:
  upload-dir: C:\Users\jizhi\Downloads\
  api-path: http://192.168.1.3:8080/uploads/