#Tomcat
server:
  port: 8080
# DataSource
spring:
  datasource:
    dynamic:
      primary: fluxWcs
      strict: false
      datasource:
        fluxWcs:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.200.153:3306/wcsdb?characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: fluxwcs123

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB

mybatis:
  type-aliases-package: com.eTag.back.*.pojo
  mapper-locations: classpath:mapping/*/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

page helper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  auto-runtime-dialect: true

logging:
  level:
     com.eTag.back.* : DEBUG

